### ISSUE TITLE
Consider adding configuration files to allow opening the workshop repo in my binder.org

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-workshop#106]

**Comment by eteq** [comment]
We (myself, @pllim, @stargaser, and @adrn) discussed this in-person at the coordination meeting.

There is also an option for "use someone's Jupyterhub", and @stargaser has a possible connection there (as do I) but binder is probably best if we can make it work because it depends on no specific institutional connections

**Comment by adrn** [comment]
This took 2 seconds for me to try, so I cloned the repo into our binderhub instance at Flatiron in case it'd be useful: https://binder.flatironinstitute.org/v2/user/apricewhelan/aas-astropy

I'm not actually sure what the default permissions are, so I guess see if you can access that page?

**Comment by pllim** [comment]
Works for me! :tada:  Can we consider this done then?

**Comment by stargaser** [comment]
Works for me too! 🎉

**Comment by stargaser** [comment]
I'm trying this on mybinder.org now. I thought that maybe the `environment.yml` has to be in the root directory, but perhaps it is found in the subdirectory?

**Comment by stargaser** [comment]
The answer to that is: No, repo2docker does not find environment.yml in a subdirectory. I think that just a soft link from the current environment.yml to the root of the repo is all we need, together with a launch binder badge.
