### ISSUE TITLE
Schedule post-workshop survey email

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-workshop#128]
In past years, I have scheduled an email with a link to the post survey to send to all workshop participants (bcc'd) about 30mins before the workshop is scheduled to end. That way, it's in their inbox at the right time. Do y'all want me to do this again or are y'all on top of it?

**Comment by stargaser** [comment]
I've been handling the emails to participants for this workshop. I'll set up this email. We have the post-workshop survey in-hand already.

**Comment by pllim** [comment]
@stargaser , is it set up?

**Comment by stargaser** [comment]
I have drafted the email like this:

> Hello workshop participants,
Thank you for participating in today's workshop. Please take a few minutes to fill out our survey at (link).
Regards,
David for the workshop team

I'm not planning to PR this one since it is short. But if more needs to be said, please comment here.

I'm worried I'll accidentally send it too early, so I'll copy in the email addresses in the afternoon. Maybe after doing a test schedule send to myself just to make sure there's no timezone issue....

**Comment by pllim** [comment]
Sounds good. Thanks, @stargaser!
