### ISSUE TITLE
Photutils, WCS, and Modeling could use exercises that are more fun

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-workshop#13]

**Comment by sosey** [comment]
and also show more concrete examples of use  :-)

**Comment by stargaser** [comment]
The WCS exercises at AAS 231 were copied from AAS 229 and these revolved around a very specialized use of SIP for the Advanced Camera for Surveys.

It might be better to have an exercise for someone to set up a simple WCS (no distortion). Definitely some exercises just showing coordinate conversions would be good.

As part of WCS I also presented wcsaxes as an application. The example was made at last-minute and was also not good in my opinion.

**Comment by sosey** [comment]
modeling notebook updated in https://github.com/astropy/astropy-workshop/pull/17

**Comment by pllim** [comment]
More fun... in what way?

**Comment by stargaser** [comment]
As I recall, the title of this issue came from feedback from the AAS's survey of participants at AAS 231 (Jan 2018). I think "fun" means "interesting" or "useful to many astronomers and somewhat challenging".

 Modeling exercises have since been updated.

The WCS exercises felt to me (at AAS 231 where I presented them) like uninteresting bookkeeping -- modify one keyword and write back to a file; make an alternate WCS which users rarely need to do.

Participants had difficulty with the visualization exercises and the exercise solution results were not much different from the examples. More fun could be "asinh stretch" on some spiral galaxies, or making 3-color images "Lupton-style" on the same.

Photutils, we probably need a separate issue? I haven't thought about those.

**Comment by stargaser** [comment]
I just saw  astropy/astropy#9469 adds a function to compute a WCS from a set of points. If people are using astropy 4.0 for the workshop, that could be the basis of a fun WCS exercise.

**Comment by bsipocz** [comment]
4.0 will be (hopefully) or will not be (a possibility) out at the time of the workshop, we haven't yet started RC testing.
So I would not count on it.

**Comment by pllim** [comment]
@stargaser , does #130 really completely resolve this issue? What about `photutils` and `modeling`?

I am re-opening this, just in case. If it is really completely resolved, please close it (again). Thanks!

**Comment by pllim** [comment]
Reading the thread again, looks like @sosey took care of `modeling`. `phoutils` is probably taken care of between @larrybradley and @shannnnnyyy . And last but not least, WCS by @stargaser . So, I am reversing my earlier decision and closing this issue now.

If more fun is to be had, please open new issue(s) with specifics. Thanks!
