### ISSUE TITLE
Decide whether participants use `jupyter notebook` or `jupyter lab`

### ISSUE THREAD

**Issue by stargaser** [astropy/astropy-workshop#98]
In reviewing #97 I realized I have been tacitly assuming we'd use Jupyterlab instead of Jupyter notebook for the workshop. Currently our intro materials show `jupyter notebook` and #97 will introduce `jupyter notebook` as part of the installation instructions.

I'd like to discuss this at the coordination meeting. In favor of Jupyterlab, it is now well past the 1.0 release and I believe all the tutorials I saw at SciPy 2019 were using it.

**Comment by pllim** [comment]
Is there a need to switch to Lab? Are we popping out windows?

**Comment by stargaser** [comment]
We don't _need_ to have Lab for the workshop. I would defer to the comfort level of the presenters and the helpers. I'd like to take a quick poll at the coordination meeting to see where people are at.

Also curious what @bmorris3 has shown in recent workshops.

I'm happy to drop this if people are uncomfortable with Lab.

**Comment by bmorris3** [comment]
@stargaser – I've been using notebook rather than lab for the workshops (even though I use lab for all of my work), partly because there's at least one demo that works better in notebook (using `%matplotlib notebook` without installing plugins), and partly because it's what most people already know. That allows you to spend a bit less time introducing the notebook environment and more time on the contents.

**Comment by pllim** [comment]
We will leave the instructions as is, i.e., mentioning notebooks. However, we will also not stop people if they already use lab.
